### ISSUE TITLE
JScript

### ISSUE THREAD

**Issue by NicoSgandurra** [CodeSystem2022/PrimatesCuartoSemestre#6]

**Comment by NicoSgandurra** [comment]
Hola osman, en el repositorio no figura cargada la asistencia, podrías revisarla?

**Comment by OsmanH25** [comment]
Hola Nico! Mas tardecito la cargo y me cambio a la semana 2 para dejarla
armada...

**Comment by OsmanH25** [comment]
Hola, soy Luciano Marcos, conductor profesional con amplia experiencia en
transporte de pasajeros y carga, y más de 10 años en logística y atención
al cliente. Cuento con licencias habilitantes A1.2, C2, D1, D3 y E2, y
experiencia en gestión de rutas, entregas y operaciones. Adjunto mi CV con
referencias comprobables. Quedo a su disposición.

TEL:  2995808400
